GET https://todolist-api-lj47.onrender.com/todos

###

POST https://todolist-api-lj47.onrender.com/todo/new
Content-Type: application/json

{
    "text": "Have a second beer"
}

###

DELETE https://todolist-api-lj47.onrender.com/todo/delete/64f2fc8391aed48e84debb47

###

PUT https://todolist-api-lj47.onrender.com/todo/complete/64f2fc8391aed48e84debb47

###

POST http://localhost:3001/register