GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Have a second beer"
}

###

DELETE http://localhost:3001/todo/delete/64d4efb205a3dd1ab6dbdb54
###

PUT http://localhost:3001/todo/complete/64d8aa6f6bcac83a54738962